#!/bin/bash

if [[ "$(docker ps | grep martine-rds 2> /dev/null)" != "" ]]; then
  docker kill martine-rds
  docker rm -f martine-rds
fi

# create db container
docker-compose -f ./cicd/db.compose.yaml up -d