# Use mysql/example user/password credentials
version: "3"

services:
  db:
    image: mysql
    restart: always
    container_name: martine-rds
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
