#!/usr/bin/env node

const mysql = require('mysql2/promise');
const categories = require("./categories");
const { dbUser, dbPassword, dbName } = require("../envVars");
const { hash } = require('../services/tokenService');

const main = async () => {

  //establish connection to the database
  const connection = await mysql.createConnection(`mysql://${dbUser}:${dbPassword}@0.0.0.0:3306/${dbName}`);

  // console log admin user is initiated
  console.log('Inserting admin user...');

  // establishing admin user and hashed password  
  await connection.query('INSERT INTO users SET ?', {
    username: process.env.ADMIN_USER,
    passwordDigest: await hash(process.env.ADMIN_PASSWORD)
  });

  // console log process has begun inserting categories
  console.log('Inserting categories...');

  // map the categories object and return promises.......all requests to the database happen simultaniously 
  await Promise.all(Object.values(categories.categories).map(async (category) => {

    // id is auto generated by mysql
    console.log(`Inserting category ${category.title}`);

    //insert into categories table row ....... this is happening within the loop
    return await connection.query('INSERT INTO categories SET ?', { title: category.title, route: category.route });
  }));

  // console log process finised
  console.log('Done. Exiting');

  process.exit(1);
}
main();







